# Generated by Django 4.0.4 on 2022-06-02 14:50

from django.db import migrations, models
import retailapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='retail_info',
            fields=[
                ('retail_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number1', models.BigIntegerField()),
                ('contact_number2', models.BigIntegerField(blank=True, null=True)),
                ('retail_size', models.IntegerField()),
                ('it_automation', models.CharField(max_length=50)),
                ('no_of_mobile', models.IntegerField()),
                ('no_of_tab', models.IntegerField()),
                ('no_of_computer', models.IntegerField()),
                ('no_of_printer', models.IntegerField()),
                ('no_of_scanner', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to=retailapp.models.upload_to, verbose_name='Image')),
            ],
        ),
    ]
